downloads_folder: 'test_data'
filename_stem: "DTC_UAT_testtracking_ROE_TEST"
database_path: 'data/test_coordination_TEST.db'
skiplog_folder: 'output/skiplog'
archive_enabled: false

imports:
  defects:
    enabled: true
    sheet_name: "Defects"
